version: '3'
services:
  www:
    image: nginx
    volumes:
      - "./html:/usr/share/nginx/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
